# image will be published to ghcr.io/<user>/<name>
name: iamblu
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      - starship
      - fish
    remove:
      - distrobox

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      install:
        - io.gitlab.librewolf-community
        - com.bitwarden.desktop
        - com.mattjakeman.ExtensionManager
        - com.spotify.Client
        - com.valvesoftware.Steam
        - dev.vencord.Vesktop
        - org.mozilla.Thunderbird
      remove:
        # - org.gnome.eog
  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
      repo-name: gnome-nightly
      repo-title: "GNOME Nightly (system-wide)"
      install:
        - org.gnome.Ptyxis.Devel

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
